@AttendanceTracker1_HostAddress = https://localhost:7009

GET {{AttendanceTracker1_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{AttendanceTracker1_HostAddress}}/api/overtime

###
